export const landingPageCatchPhrases = [
    "Lachen ist die beste Medizin – und bei uns ist sie kostenlos!",
    "Wir liefern den Humor, du genießt die Wirkung – täglich direkt in deinem Posteingang!",
    "Mach Schluss mit langweiligen Tagen – unsere Witze bringen frischen Wind in deinen Alltag!",
    "Ein Lächeln am Morgen vertreibt Kummer und Sorgen!",
    "Wir sind wie der Kaffee des Humor – aber ohne Koffein, dafür mit mehr Lachen!",
    "Fühlst du dich manchmal wie ein Mensch, der keinen Sinn für Humor hat? Unsere Witze sind die Heilung!",
    "Ein Tag ohne Lachen ist wie ein Himmel ohne Sonne – lass uns die Wolken vertreiben!",
    "Wir garantieren: Unsere Witze sind besser als die deiner Oma. Probiere es aus!",
    "Melde dich an um zu erfahren, warum unser Newsletter der Grund für deine Büro-Kichern-Attacken wird!",
    "Hol dir den täglichen Lacher direkt in deinen Posteingang – du wirst deinen Spam-Ordner lieben!",
    "Unsere Witze sind wie Kekse – es gibt nie genug davon. Hol dir jeden Tag einen Frischen!",
    "Sei die lustigste Person im Raum – mit dem einzigen Newsletter, der garantiert für Lacher sorgt!",
    "Wir garantieren: Kein E-Mail-Postfach ist komplett ohne unsere täglichen Lacher. Sei dabei!",
    "Unsere Witze sind wie kleine Party-Feuerwerke für deine Inbox. Mach mit und erlebe den Spaß!",
    "Wenn du dachtest, dass E-Mails nur Arbeit bedeuten – dann hast du unseren Newsletter noch nicht ausprobiert!",
    "Glaube nicht an Glück – glaub an unseren Witz-Newsletter! Jede E-Mail ist ein Gewinn für dein Lächeln!",
    "Schau nicht auf die Uhr – schau in deinen Posteingang! Dort wartet ein täglicher Lacher auf dich!",
    "Wie nennt man einen langweiligen Tag? Den, an dem du unseren Newsletter nicht abonniert hast!",
    "Unsere E-Mails sind wie Humor-Taxis – wir bringen dich von Langeweile zu Lachen in Sekunden!",
    "Unsere Witze sind wie ein Keks aus dem Intergalaktischen Supermarkt – sie kommen aus einer anderen Dimension der Lustigkeit!",
    "Unsere Witze sind wie ein Tretroller im Wolkenkratzer – sie bringen dich auf unerwartete Höhen des Lachens!",
    "Unsere Witze sind wie ein Einhorn auf einem Regenbogen – sie sind selten und bringen magische Lacher in dein Leben!",
    "Unsere Witze sind wie eine Tasse Kaffee, die von Aliens serviert wird – exotisch, überraschend und garantiert unvergesslich!",
    "Unsere Witze sind wie ein Schokoriegel für deinen Verstand – süß, aber mit einem Hauch von verrücktem Humor!",
    "Unsere Witze sind wie ein Zirkus in deinem Posteingang – laute Lacher, schillernde Überraschungen und jede Menge Spaß!",
    "Unsere Witze sind wie ein Flummi auf einem Trampolin – sie hüpfen dich direkt ins Herz der guten Laune!",
    "Unsere Witze sind wie ein geheimnisvolles Rezept aus der Zeitmaschine – sie bringen Geschmackserlebnisse aus der Zukunft!",
    "Unsere Witze sind wie ein Kühlschrank, der nach Mitternacht aufmacht – sie sind immer eine unerwartete Freude!",
    "Unsere Witze sind wie ein Lamas, das in deinem Garten tanzt – außergewöhnlich, aber garantiert amüsant!",
    "Unsere Witze sind wie ein Schaf in einem Anzug – völlig unerwartet und absolut zum Lachen!",
    "Unsere Witze sind wie ein Puzzle, das du rückwärts zusammensetzt – sie ergeben immer einen überraschenden Spaß!",
    "Unsere Witze sind wie ein magisches Trampolin – je mehr du springst, desto höher geht der Spaß!",
    "Unsere Witze sind wie ein fliegender Teppich – sie nehmen dich mit auf eine humorvolle Reise ohne Grenzen!",
    "Unsere Witze sind wie ein Konfetti-Regen aus dem Weltall – bunt, chaotisch und immer ein Grund zum Feiern!",
    "Unsere Witze sind wie Schokolade – sie machen das Leben süßer und sind immer willkommen!",
    "Unsere Witze sind wie ein Kühlschrank – sie bringen dich zum Lächeln, egal wie oft du nachschaust!",
    "Unsere Witze sind wie ein Regenschirm – sie schützen dich vor trüben Tagen und bringen ein Lächeln!",
    "Unsere Witze sind wie Kaffeepausen – sie sind kurz, aber machen den Tag besser!",
    "Unsere Witze sind wie Popcorn – du kannst nie genug davon haben und sie machen immer Spaß!",
    "Unsere Witze sind wie ein Spaziergang im Park – sie bringen frischen Wind und gute Laune!",
    "Unsere Witze sind wie ein heißer Kakao an einem kalten Tag – sie wärmen dich von innen heraus!",
    "Unsere Witze sind wie ein kleiner Schatz – jeden Tag gibt es etwas Neues zu entdecken und zu lachen!",
    "Unsere Witze sind wie ein Überraschungsei – du weißt nie, was du bekommst, aber es wird dich zum Lachen bringen!",
    "Unsere Witze sind wie ein gutes Buch – sie sind spannend, unterhaltsam und machen süchtig nach mehr!",
    "Unsere Witze sind wie ein guter Freund – sie sind immer für dich da, wenn du eine Aufmunterung brauchst!",
    "Unsere Witze sind wie ein Partyhut – sie machen jeden Tag bunter und fröhlicher!",
    "Unsere Witze sind wie ein Lächeln – sie sind ansteckend und machen die Welt ein kleines Stück besser!",
    "Unsere Witze sind wie eine tägliche Dosis Vitamin C – sie stärken deine Laune und bringen Farbe in deinen Tag!",
    "Unsere Witze sind wie ein guter Film – sie bringen dich zum Lachen und machen alles besser!",
    "Unsere Witze sind wie ein tanzender Tintenfisch auf einem Einrad – total verrückt und garantiert zum Lachen!",
    "Unsere Witze sind wie ein Kühlschrank voller schwebender Puddingbecher – unerwartet und einfach köstlich!",
    "Unsere Witze sind wie ein Sessel, der plötzlich ein Jetpack hat – überraschend und bringt dich in neue Höhen des Lachens!",
    "Unsere Witze sind wie ein Zirkus von sprechenden Katzen – seltsam, faszinierend und unendlich unterhaltsam!",
    "Unsere Witze sind wie ein fliegendes Sandwich – sie kommen aus dem Nichts und landen direkt auf deinem Lächeln!",
    "Unsere Witze sind wie ein schwimmender Keks im Vulkan – heiß, ungewöhnlich und voller Überraschungen!",
    "Unsere Witze sind wie ein Hula-Hoop-Reifen aus Zuckerwatte – süß, wirbelnd und kaum zu fassen!",
    "Unsere Witze sind wie ein Piratenschiff auf einem Ozean aus Limonade – Abenteuer und Lachen sind garantiert!",
    "Unsere Witze sind wie ein Wackelpudding auf einem Trampolin – sie hüpfen direkt in dein Herz und bringen viel Spaß!",
    "Unsere Witze sind wie ein Roboter, der Komplimente verteilt – sie sind so gut programmiert, dass sie dich ständig zum Lachen bringen!",
    "Unsere Witze sind wie ein fliegender Kühlschrank voller Einhörner – ungewöhnlich, magisch und ein Genuss für dein Lächeln!",
    "Unsere Witze sind wie ein intergalaktischer Tanzwettbewerb – verrückt, wild und definitiv eine Erfahrung der Extraklasse!",
    "Unsere Witze sind wie ein Würfelschachtel voller Überraschungen – jeder Wurf ist eine neue Chance auf Lachen!",
    "Unsere Witze sind wie ein Zelt voller Kängurus mit Clownsnasen – chaotisch, komisch und immer für eine Überraschung gut!",
    "Unsere Witze sind wie ein geheimnisvoller Keks, der beim Essen plötzlich singt – unerwartet und immer ein Hit für deine Lachmuskeln!",
    "Bei diesen Witzen sind alle Kranplätze verdichtet!",
    "Diese Witze kicken härter als Red Bull!",
    "Vorsicht: Lachflash-Gefahr!",
    "Deine Lachmuskeln werden dir danken (oder fluchen).",
    "Witze so gut, dein Crush wird beeindruckt sein.",
    "Wer diese Witze nicht lustig findet, hat keinen Humor.exe",
    "Achtung: Kann zu unkontrollierbarem Grinsen führen.",
    "Deine Stimmung? Lifted. Dein Humor? Upgraded.",
    "Witze, die sogar deine Oma zum Lachen bringen.",
    "Lachen garantiert oder dein Geld zurück (Moment, die Seite ist ja kostenlos).",
    "Diese Witze sind der perfekte Icebreaker für dein nächstes Date.",
    "Lachkrampf-Alarm: Erste-Hilfe-Koffer bereithalten!",
    "Witziger als deine TikTok-For-You-Page.",
    "Schnallt euch an, die Lach-Achterbahn geht los!",
    "Witze schärfer als deine Snapchat-Filter.",
    "Deine Lachmuskeln werden brennen wie nach dem Leg Day.",
    "Vorsicht: Kann zu plötzlichen Lachausbrüchen in der Bahn führen.",
    "Lustiger als die Memes in deinen Gruppen-Chats.",
    "Diese Witze sind der echte Mood-Booster.",
    "Wer nicht lacht, hat sein WLAN ausgeschaltet.",
    "Witze fresher als dein Spotify Wrapped.",
    "Lachen bis der Akku leer ist – und dann weiter!",
    "Diese Jokes sind deine neue Lieblings-Playlist.",
    "Witze, die sogar deine Katze zum Schmunzeln bringen.",
    "Bezahlte Comedycoaches hassen diesen Trick!",
    "Tradeoffer! Wir bekommen: glückliche Abonennten - Du bekommst: Täglich Spaß",
    "Deine Streakzahl auf Snapchat vs. die Anzahl deiner Lacher hier.",
    "Lachen ist hier das neue Swipen.",
    "Diese Witze sind legitimer Grund, das Handy im Unterricht zu checken.",
    "Emails lesen macht endlich wieder Sinn!",
    "Make Emails lesen great again!",
    "Wer diese Witze teilt, wird zum Clown der Gruppe (im positiven Sinne).",
    "Lustiger als die Autokorrekturfails deiner Eltern.",
    "Diese Witze bringen dich schneller zum Lachen als dein Internet-Speed.",
    "Warum zum Comedyclub gehen, wenn du diese Website hast?",
    "Witze so fire, dein Handy könnte schmelzen!",
    "Diese Witze sind deine neue Prokrastinations-Ausrede.",
    "Humor-Level: über 9000!",
    "Witze lustiger als deine letzte Tinder-Story.",
    "Lachen guaranteed oder Taschengeld zurück.",
    "Witziger als deine Browser-Chronik.",
    "Lachfalten sind die neuen Likes.",
    "Diese Witze sind der wahre Trend.",
    "Mehr Spaß als deine Lieblings-Memes.",
    "LOL steht für 'Lese Oft (und) Lache'.",
    "Witze, die sogar dein Crush lustig findet.",
    "Deine tägliche Dosis Dopamin.",
    "Diese Jokes sind der Grund, warum dein Akku immer leer ist.",
    "Witziger als alle Emojis zusammen.",
    "Lachen ist hier das neue Binge-Watching.",
    "Diese Witze machen süchtiger als Smartphone-Games.",
    "Dein Gesicht nach diesen Witzen: 🤣",
    "Witze, die dich zum Klassenclown machen (ohne Aufwand).",
    "Deine grumpy Freunde hassen diesen Newsletter!"
]