# Generated by Django 5.0.7 on 2024-08-13 22:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joke_newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterreciever',
            name='activation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='newsletterreciever',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
