FROM python:3.11-slim-bookworm

WORKDIR /app/backend

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY ./bin/entrypoint.sh ./bin/
RUN sed -i 's/\r$//g' /app/backend/bin/entrypoint.sh
RUN chmod +x /app/backend/bin/entrypoint.sh

COPY . .

ENTRYPOINT ["/app/backend/bin/entrypoint.sh"]