# Generated by Django 5.0.7 on 2024-08-16 21:18

import jokes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jokes", "0002_submittedjoke"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jokepicture",
            name="image",
            field=models.ImageField(
                upload_to=jokes.models.get_joke_picture_upload_path
            ),
        ),
    ]
