# Generated by Django 5.0.7 on 2024-10-30 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0003_alter_jokepicture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='joke_of_the_day_selection_weight',
            field=models.IntegerField(default=10, help_text='Weight for Joke of the Day selection (1-100). Higher values increase selection probability.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
