# Generated by Django 5.0.7 on 2024-11-01 12:59

import django.db.models.deletion
import jokes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0004_joke_joke_of_the_day_selection_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareableImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=jokes.models.get_shareable_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('joke', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shareable_image', to='jokes.joke')),
            ],
        ),
    ]
