# Generated by Django 5.0.7 on 2026-08-25 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jokes', '0005_shareableimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('feed', 'Feed'), ('story', 'Story')], max_length=8)),
                ('media_pk', models.CharField(max_length=64)),
                ('is_backfill', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_shares', to='jokes.joke')),
            ],
            options={
                'indexes': [models.Index(fields=['posted_at'], name='socials_sha_posted__7f15b1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='instagramshare',
            constraint=models.UniqueConstraint(fields=('joke', 'kind'), name='unique_joke_share_per_kind'),
        ),
    ]
